- name: install package 
  hosts: all 

  tasks:
  - name: install chrome package
    register: command_output
    win_chocolatey:
      name: googlechrome
      state: present
      ignore_checksums: yes

